name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: compress program
        run: |
          mkdir citest
          cp test.py compare.py citest
          tar -czf citest.tar.gz citest
      - name: upload package
        uses: actions/upload-artifact@v2
        with:
          name: citest
          path: citest.tar.gz

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: download package
        uses: actions/download-artifact@v2
        with:
          name: citest

      - name: unpack program
        run: tar -xzf citest.tar.gz --strip-components=1

      - name: Run program
        run: python3 test.py

      - name: upload benchmark result
        uses: actions/upload-artifact@v2
        with:
          name: benchmark
          path: run_results.json

  compare:
    needs: run
    runs-on: ubuntu-latest

    steps:
      - name: download package
        uses: actions/download-artifact@v2
        with:
          name: citest

      - name: download results
        uses: actions/download-artifact@v2
        with:
          name: benchmark

      - name: unpack program
        run: tar -xzf citest.tar.gz --strip-components=1

      - name: get old benchmark results
        uses: actions/checkout@v2
        with:
          ref: benchmark_results
          path: benchmark_results_old

      - name: Save benchmark results
        run: |
          rm -rf benchmark_results_new
          mkdir benchmark_results_new
          cp run_results.json benchmark_results_new/

      - name: Deploy results to git
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./benchmark_results_new
          publish_branch: benchmark_results
          enable_jekyll: true

      - name: Run comparison
        run: python3 compare.py benchmark_results_old/run_results.json run_results.json
