# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          ref: benchmark_results
          path: benchmark_results_old

      # Runs a single command using the runners shell
      - name: Run benchmark
        run: python3 test.py

      - name: Save benchmark results
        run: |
          rm -rf benchmark_results_new
          mkdir benchmark_results_new
          cp run_results.json benchmark_results_new/

      - name: Deploy results to git
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./benchmark_results_new
          publish_branch: benchmark_results

      # Runs a set of commands using the runners shell
      - name: Run comparison
        run: python3 compare.py benchmark_results_old/run_results.json run_results.json
